CREATE TABLE IF NOT EXISTS mytable(
   sku       INTEGER  NOT NULL PRIMARY KEY 
  ,name      VARCHAR(36) NOT NULL
  ,category  VARCHAR(34) NOT NULL
  ,stock     INTEGER  NOT NULL
  ,min_stock INTEGER  NOT NULL
  ,location  VARCHAR(20) NOT NULL
  ,value     NUMERIC(6,2) NOT NULL
);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (1,'Honey Garlic Chicken','Prepared Poultry',236,68,'Pirok',8.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (2,'Lemon Herb Chicken','Marinated Poultry',83,188,'Elías',7.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (3,'Portable Solar Generator','Outdoor Accessories',528,109,'Covas da Raposa',399.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (4,'Ranch Dressing','Dressing',6,163,'Saint-Pierre',2.59);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (5,'Adjustable Standing Desk','Furniture',292,86,'Buldon',299.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (6,'Sliced Ham','Processed Meats',138,177,'Fada',5.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (7,'Sliced Ham','Processed Meats',623,110,'Jiulong',5.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (8,'Peach Mango Smoothie','Smoothies',330,64,'Ondo',3.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (9,'Fresh Basil Pesto','Herb-Based Sauces',244,50,'Kamiennik',4.79);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (10,'Portable Hammock with Stand','Camping Equipment',436,129,'Sijiu',69.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (11,'Pumpkin Pie Spice','Baking Ingredients',485,175,'Eloy Alfaro',2.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (12,'Chicken Broth','Soups & Broths',821,134,'Rozsypne',2.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (13,'Honey Glazed Carrots','Prepared Vegetables',279,52,'Alegrete',3.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (14,'Buffalo Cauliflower Wings','Frozen Appetizers',303,135,'Seka',6.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (15,'Coconut Bowls Set','Dinnerware',939,198,'Santa Rosa de Cabal',22.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (16,'Vegan Protein Powder','Fitness & Nutrition',726,68,'Marco',34.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (17,'Pet Hair Removal Brush','Grooming Supplies',751,146,'Trajouce',14.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (18,'First Aid Kit','Emergency Preparedness & First Aid',541,76,'Khombole',29.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (19,'Mango Chunks','Frozen Fruits',353,137,'Guanzhuang',4.89);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (20,'Coconut Curry Chicken','Frozen Meals',173,146,'Sunja',9.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (21,'Smartwatch','Fitness Monitors',190,85,'Nowe Brzesko',199.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (22,'Car Vacuum','Car Cleaning',809,87,'Mache',49.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (23,'Golf Putting Green','Golf',545,200,'Donggou',79.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (24,'Wireless Smart Plug','Home Accessories',413,102,'Uherský Ostroh',19.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (25,'Portable Air Compressor','Automotive Tools',862,189,'Mayorga',44.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (26,'Granulated Sugar','Baking Ingredients',251,191,'Anju',2.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (27,'Buffalo Wing Sauce','Hot Sauces',16,147,'Jianshe',3.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (28,'Repair Tool Set for Home Improvement','Hand Tools',612,158,'Nagornyy',29.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (29,'Instant Read Meat Thermometer','Cooking Tools & Utensils',945,158,'Kovači',24.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (30,'Salsa Verde','Sauces',917,59,'Sakai-nakajima',3.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (31,'Organic Coconut Sugar','Baking Ingredients',124,195,'Mulchén',4.19);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (32,'Mechanical Pencil Set','Writing Instruments',942,187,'Shitang',19.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (33,'Rainbow Veggie Chips','Healthy Snacks',222,99,'Landskrona',3.29);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (34,'Ginger Turmeric Shots','Health Drinks',454,63,'Staraya Mayna',3.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (35,'Frozen Hash Browns','Frozen Potato Products',402,90,'Xuri',2.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (36,'Teriyaki Salmon Fillets','Prepared Seafood',996,32,'La Cruz',9.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (37,'Coconut Curry Lentils','Canned Vegetarian Meals',162,135,'Kurlovo',5.79);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (38,'Electric Milk Frother','Beverage Appliances',940,147,'San Antonio',19.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (39,'Banana Nut Muffins','Muffins',52,189,'Kalývia',4.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (40,'Portable Hammock Swing','Outdoor Furniture',213,15,'Kasama',59.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (41,'Portable Refrigerator Freezer','Camping Equipment',640,93,'Jiaocha',299.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (42,'Nutty Trail Mix','Healthy Snacks',319,91,'Kremidivka',4.29);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (43,'Coconut Chia Pudding','Dairy Alternatives',775,63,'Calape',3.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (44,'Fishing Tackle Box','Fishing Equipment',923,149,'Sipe Sipe',24.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (45,'Home Cleaning Robot','Robotic Cleaners',492,80,'Longfengba',249.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (46,'Vegetable Spiralizer','Food Preparation Tools',934,196,'Daniwato',19.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (47,'Tahini','Nut Butters',635,159,'Shunling',5.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (48,'Window Bird Feeder with Suction Cups','Bird Feeding Accessories',113,42,'Manturovo',28.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (49,'Kitchen Scale','Kitchen Gadgets',41,183,'Haibara',19.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (50,'LED Desk Light','Lighting & Lamps',751,47,'Kourou',34.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (51,'Basil Lemonade','Herbal Beverages',71,59,'San Isidro',2.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (52,'Pressure Washer Accessories Kit','Outdoor Cleaning',401,71,'Ruy Barbosa',39.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (53,'Gardening Gloves','Garden Tools',552,41,'Lisui',15.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (54,'Garlic Herb Cream Cheese','Cheese Spreads',723,80,'Rulenge',2.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (55,'Shoe Organizer','Home Organization',929,192,'Starobaltachevo',39.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (56,'Chickpea Salad','Salads',320,102,'Rios Frios',5.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (57,'Lentil Vegetable Curry','Vegetarian Meals',664,132,'Pérama',4.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (58,'Camping Chair with Cooler','Camping Equipment',149,124,'Yuanquan',49.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (59,'Ergonomic Gaming Chair','Gaming Accessories',756,146,'Kaset Wisai',199.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (60,'Cat Tree with Scratching Posts','Cat Furniture',393,142,'Viçosa do Ceará',79.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (61,'Classic Pumps','Women''s Dress Shoes',966,160,'Shiqiao',64.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (62,'Fettuccine Alfredo Dinner Kit','Meal Kits - Pasta',706,159,'Khóra',5.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (63,'Wireless Game Controller','Gaming Accessories',611,59,'Chernyshevsk',39.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (64,'Ice Cream Scoop','Kitchen Gadgets',146,10,'Krajan Jabungcandi',12.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (65,'Green Tea Matcha Powder','Tea',943,53,'Adjumani',15.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (66,'Brussels Sprouts','Vegetables',173,198,'Lobos',3.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (67,'Mango Salsa','Salsas',321,81,'Ngembo',3.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (68,'Portable Air Conditioner','Cooling Appliances',669,96,'Bang Bua Thong',299.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (69,'Heated Throw Blanket','Bedding & Linens',579,112,'Pardubice',49.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (70,'Guitar Tuner','Accessories',990,142,'Priupskiy',19.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (71,'Chipotle Seasoning Blend','Regional Seasoning Blends',538,198,'Kudang',2.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (72,'Portable Bluetooth Headphones','Wireless Audio Accessories',993,192,'Koszarawa',79.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (73,'Comfortable Jogger Pants','Bottoms',483,120,'Najrān',29.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (74,'Recipe Book Stand','Kitchen Accessories',560,188,'Kaiyun',22.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (75,'Digital Thermostat','Smart Home & Security',313,176,'Ciechanowiec',59.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (76,'Biodegradable Dog Waste Bags','Dog Supplies',504,153,'Dīla',14.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (77,'Electric Toothbrush Holder','Oral Care & Hygiene',943,121,'Ershilipu',14.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (78,'High-Top Leather Boots','Boots',721,51,'La Escondida',99.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (79,'Spicy Garlic Edamame','Savory Snacks',282,177,'Macapo',3.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (80,'Lemon Herb Chicken','Marinated Poultry',743,200,'Cubatão',7.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (81,'Granola Cereal','Granola/Cereal',160,135,'Yuecheng',4.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (82,'Fruit and Nut Medley','Nuts and Trail Mix',400,120,'Albarraque',5.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (83,'Sriracha Chili Sauce','Hot Sauces',258,163,'Šoštanj',2.79);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (84,'Quinoa and Kale Salad Kit','Meal Kits',279,55,'Igir-igir',5.29);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (85,'Lightweight Workout Tank','Tanks & Sleeveless Tops',398,52,'Dagar',29.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (86,'Almond Flour Tortillas','Baking Ingredients',263,16,'Shuanghe',4.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (87,'Chickpea Pancakes','Frozen Meals',235,167,'Örnsköldsvik',4.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (88,'Electric Razor','Personal Care & Grooming',909,77,'La Libertad',59.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (89,'Spicy Salsa Verde','Salsas',742,89,'Bayshint',3.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (90,'Noise-Canceling Earbuds','Headphones & Earbuds',554,96,'Malamig',79.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (91,'Balsamic Glaze','Sauces',145,79,'Akhfennir',4.79);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (92,'Chickpea Salad Deluxe','Prepared Salads',823,25,'Poja Nae',4.29);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (93,'Peach Yogurt','Yogurt',705,133,'Guxi',1.29);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (94,'Peach Yogurt','Yogurt',27,106,'Emmen',1.29);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (95,'Watercolor Paint Set','Painting Supplies',181,110,'Barisan',19.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (96,'Wireless Car Charger','Phone Accessories',201,13,'Novorozhdestvenskaya',24.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (97,'Garlic & Herb Goat Cheese','Cheese',886,96,'Västerås',5.49);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (98,'Adjustable Dumbbells','Strength Training Equipment',246,71,'Xizhong',249.99);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (99,'Balsamic Glaze','Sauces',522,64,'São Mateus',4.79);
INSERT INTO mytable(sku,name,category,stock,min_stock,location,value) VALUES (100,'Foot Massager Machine','Wellness & Relaxation',912,38,'Xiaohe',59.99);
