create table MOCK_SHIPPING_DATA (
	date DATE,
	id INT,
	item VARCHAR(50),
	quantity INT,
	value VARCHAR(50),
	source_customer VARCHAR(50),
	responsible VARCHAR(50),
	in_out VARCHAR(3)
);
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('17/06/2025', 1, 'Teriyaki Chicken Stir-Fry', 9, 6.99, 'Leenti', 'Lolita Stoneley', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('16/03/2025', 2, 'Insulated Coffee Mug', 43, 24.99, 'Kazu', 'Odelinda Gleder', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('21/11/2025', 3, 'Warm Knit Beanie', 49, 19.99, 'Kazu', 'Leisha Bromet', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('12/08/2025', 4, 'Artisan Flatbreads', 44, 2.99, 'Wikido', 'Worthy McCreery', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('13/08/2025', 5, 'Maple Glazed Carrots', 38, 3.29, 'Topicware', 'Edwin Thorsby', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('01/04/2025', 6, 'Spinach Feta Wraps', 64, 4.29, 'Aimbo', 'Aurlie Guille', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('22/06/2025', 7, 'Honey Nut Cheerios', 27, 4.29, 'Divavu', 'Marlowe Holdforth', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('15/09/2025', 8, 'Essential White Button-Up', 15, 44.99, 'Mydo', 'Karoline Cubbin', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('26/09/2025', 9, 'Satin Slip Dress', 44, 59.99, 'Wordware', 'Coriss Perrone', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('12/12/2025', 10, 'Roasted Garlic Aioli', 86, 3.79, 'Snaptags', 'Anna-maria Bazire', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('16/09/2025', 11, 'Kids'' Dinosaur-Themed Lunchbox', 47, 19.99, 'LiveZ', 'Cecilius Windebank', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('13/05/2025', 12, 'Desk Organizer Set', 20, 29.99, 'Skyba', 'Adelina Ather', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('22/10/2025', 13, 'Miso Dressing', 49, 3.49, 'Pixope', 'Dalenna Yakunikov', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('19/11/2025', 14, 'Spicy Avocado Salsa', 39, 4.49, 'Flipbug', 'Dov Dami', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('04/03/2025', 15, 'Surimi Crab Sticks', 12, 4.19, 'Pixonyx', 'Kati Duerden', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('23/05/2025', 16, 'Dog Waste Bag Dispenser', 31, 6.99, 'Jatri', 'Petronille Windmill', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('04/09/2025', 17, 'Peach Salsa', 15, 3.29, 'Leenti', 'Amandi Baiden', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('21/05/2025', 18, 'Tattoo Kit', 26, 99.99, 'Tazzy', 'Richie Dobsons', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('31/07/2025', 19, 'Memory Foam Pillow', 30, 39.99, 'Eazzy', 'Arri Hollindale', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('12/06/2025', 20, 'Instant Pot', 74, 89.99, 'Babblestorm', 'Ilario Wiffler', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('27/02/2025', 21, 'Ceramic Knife Set', 100, 39.99, 'Linkbuzz', 'Emera Van Vuuren', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('04/09/2025', 22, 'Peanut Butter', 33, 3.79, 'Jabberstorm', 'Duffie Trevillion', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('03/10/2025', 23, 'Pasta (Linguine)', 37, 1.89, 'Mynte', 'Maxwell Stile', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('20/03/2025', 24, 'Hot Dog Buns', 10, 2.49, 'Brainlounge', 'Elvira Scimonelli', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('23/09/2025', 25, 'Smoked Salmon', 1, 14.99, 'Jazzy', 'Jaime Winchurst', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('12/06/2025', 26, 'Cauliflower Gnocchi', 73, 3.59, 'Gabspot', 'Francyne Chrishop', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('12/12/2025', 27, 'Pet Hair Vacuum Cleaner Attachment', 55, 14.99, 'Tagtune', 'Amitie Serris', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('16/06/2025', 28, 'Athletic Compression Tights', 89, 39.99, 'BlogXS', 'Dallas Leyes', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('03/03/2025', 29, 'Portable Air Compressor', 50, 44.99, 'Thoughtworks', 'Peadar Mannakee', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('13/10/2025', 30, 'Pesto Pasta Sauce', 85, 3.99, 'Jaxworks', 'Puff Di Franceschi', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('26/11/2025', 31, 'Outdoor Picnic Blanket', 2, 34.99, 'Twitternation', 'Whitaker Hastings', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('30/08/2025', 32, 'Reusable Coffee Filter', 95, 10.99, 'Rhynyx', 'Fons Androli', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('03/10/2025', 33, 'Reusable Snack Bags', 31, 14.99, 'Bubbletube', 'Allianora Hrihorovich', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('01/06/2025', 34, 'Stylish Combat Boots', 95, 99.99, 'Kazu', 'Gard Maryman', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('12/12/2025', 35, 'Cereal Dispenser with Portion Control', 32, 24.99, 'Shuffletag', 'Helena Cage', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('30/08/2025', 36, 'Berries Medley', 50, 6.99, 'Jaloo', 'Mata Jarville', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('15/03/2025', 37, 'Multifunctional Baby Bottle Warmer', 95, 39.99, 'Devcast', 'Gerek Corrington', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('12/02/2025', 38, 'Classic Pumps', 91, 64.99, 'Twinte', 'Angele Coombes', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('03/05/2025', 39, 'Smartwatch', 70, 199.99, 'Mybuzz', 'Cherish Kalberer', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('09/06/2025', 40, 'Non-Toxic Crayons for Kids', 78, 10.99, 'Mita', 'Lina Faldo', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('25/06/2025', 41, 'Organic Vanilla Bean Ice Cream', 32, 5.99, 'Devbug', 'Audy Karpushkin', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('14/01/2025', 42, 'Reclining Camping Chair', 33, 49.99, 'Skimia', 'Wheeler Gregory', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('18/05/2025', 43, 'Measuring Cups Set', 78, 19.99, 'Centimia', 'Isis Saunton', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('23/04/2025', 44, 'Butternut Squash Soup', 100, 3.49, 'Topdrive', 'Jordan Gurrado', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('31/07/2025', 45, 'Coconut Curry Chicken', 7, 9.99, 'Mydo', 'Collin Prew', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('26/10/2025', 46, 'Vegetarian Stuffed Peppers', 93, 4.99, 'Realblab', 'Amelia Shuttle', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('02/12/2025', 47, 'Apple Juice', 29, 3.29, 'Gabvine', 'Samuele Vakhonin', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('05/02/2025', 48, 'Mediterranean Couscous Salad', 85, 5.49, 'Zoonder', 'Pasquale Rigden', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('27/12/2025', 49, 'Tomatillo Salsa', 75, 3.29, 'Skinte', 'Tatum Boggis', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('30/08/2025', 50, 'Classic White T-Shirt', 22, 19.99, 'Edgetag', 'Heather Tattersfield', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('15/01/2025', 51, 'Smart Thermostat with Wi-Fi', 73, 169.99, 'Mudo', 'Clyve Burkill', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('29/06/2025', 52, 'Chocolate Hazelnut Spread', 39, 5.99, 'Zoomlounge', 'Sharai Coast', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('17/12/2025', 53, 'Instant Mashed Potatoes', 79, 1.79, 'Podcat', 'Philippe Livingston', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('14/03/2025', 54, 'Maple Pecan Pancake Mix', 21, 4.99, 'Bubblebox', 'Vida Pau', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('01/07/2025', 55, 'Coconut Oil Spray', 59, 4.99, 'Yozio', 'Ernestine Mobius', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('12/02/2025', 56, 'Eco-Friendly Disposable Plates', 96, 22.99, 'Realcube', 'Sher Jurczik', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('18/03/2025', 57, 'Peach Mango Smoothie Mix', 50, 5.99, 'Linktype', 'Alta Arnli', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('15/02/2025', 58, 'Backpack', 90, 49.99, 'Kamba', 'Latrina Ferrey', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('27/11/2025', 59, 'Karaoke Microphone', 68, 39.99, 'Tanoodle', 'Roanna Grier', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('06/12/2025', 60, 'Kids'' STEM Robotics Kit', 55, 59.99, 'Fivespan', 'Iseabal Farge', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('21/06/2025', 61, 'Nutty Granola Clusters', 53, 2.49, 'Dynabox', 'Rory Beade', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('06/03/2025', 62, 'Apple Juice', 36, 3.29, 'Brightdog', 'Melisa Pensom', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('02/07/2025', 63, 'Chic Jumpsuit', 68, 89.99, 'Eire', 'Kaia Clewes', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('25/07/2025', 64, 'Cucumber', 13, 0.99, 'Demivee', 'Wallis Sissens', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('16/06/2025', 65, 'Classic Baseball Cap', 62, 24.99, 'Thoughtworks', 'Richy Kretchmer', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('30/05/2025', 66, 'Shower Curtain Hooks', 76, 12.99, 'Yamia', 'Aloise Vasilmanov', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('18/01/2025', 67, 'Orange Ginger Vinaigrette', 10, 3.99, 'Camido', 'Salomo Standrin', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('16/12/2025', 68, 'Bock Beer Mustard', 18, 2.29, 'Zoonoodle', 'Luca Critchard', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('11/06/2025', 69, 'Coconut Milk Ice Cream', 97, 6.99, 'Vidoo', 'Luisa Beedon', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('22/02/2025', 70, 'Honey mustard chicken tenders', 12, 7.99, 'Shuffledrive', 'Georgeta Elsmere', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('29/07/2025', 71, 'Vintage Graphic Tee', 24, 25.99, 'Jamia', 'Dewey Limpenny', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('08/05/2025', 72, 'Chipotle Black Bean Burger', 33, 4.99, 'Shuffletag', 'Elana O''Gleasane', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('14/10/2025', 73, 'Pet Carrier', 3, 39.99, 'Jatri', 'Ethelin Marmion', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('15/12/2025', 74, 'Cheddar Cheese Crackers', 71, 2.29, 'Feedspan', 'Odelia Skeggs', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('18/10/2025', 75, 'Peach Slices (canned)', 33, 2.49, 'Abatz', 'Peter Seagar', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('04/05/2025', 76, 'Fitbit Activity Tracker', 88, 99.99, 'Browsetype', 'Aimee Manlow', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('01/10/2025', 77, 'Sweet Potato Fries', 19, 3.99, 'Edgeblab', 'Chastity Janz', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('26/05/2025', 78, 'Mediterranean Chickpea Bowl', 65, 6.49, 'Skimia', 'Saleem Baldacco', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('30/06/2025', 79, 'White Rice', 79, 1.49, 'Quaxo', 'Grace Caudell', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('21/01/2025', 80, 'Motion Sensor Light', 87, 19.99, 'Twitterworks', 'Kennie Bricklebank', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('26/02/2025', 81, 'Rechargeable Hand Warmer', 6, 22.99, 'Tagpad', 'Cam Jacobsen', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('29/03/2025', 82, 'Foam Muscle Roller', 22, 24.99, 'Skilith', 'Callie Whitlow', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('26/02/2025', 83, 'Savory Rice Cakes', 29, 2.5, 'DabZ', 'Shauna Windybank', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('20/09/2025', 84, 'Electric Toothbrush', 8, 49.95, 'Youspan', 'Ximenes Print', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('21/01/2025', 85, 'Measuring Cups Set', 63, 19.99, 'Twimbo', 'Billy Jeakins', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('16/11/2025', 86, 'Woven Storage Baskets', 22, 24.99, 'Jamia', 'Bess Nana', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('28/12/2025', 87, 'Ginger Snaps', 2, 2.79, 'Lazz', 'Edwina Elden', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('23/12/2025', 88, 'Electric Rice Cooker with Steamer', 3, 49.99, 'Thoughtmix', 'Rodina Corley', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('08/11/2025', 89, 'Maple Pecan Granola', 91, 4.49, 'Bluezoom', 'Perry Feedome', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('20/03/2025', 90, 'Classic Black Trousers', 79, 54.99, 'Fliptune', 'Modesty Haryngton', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('21/09/2025', 91, 'LED Christmas Tree Lights', 70, 34.99, 'Shufflebeat', 'Osgood Dulling', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('26/10/2025', 92, 'Teriyaki Chicken Skewers', 90, 8.99, 'Avamm', 'Eden Rosevear', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('14/01/2025', 93, 'Electric Rice Cooker with Steamer', 3, 49.99, 'Browsetype', 'Diannne Collumbell', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('10/05/2025', 94, 'Savory Oatmeal Cups', 34, 1.99, 'Divanoodle', 'Kerrill Tuddall', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('27/11/2025', 95, 'Cotton Basic Tank', 95, 14.99, 'JumpXS', 'Rodger Hanner', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('20/06/2025', 96, 'Indoor Grill', 57, 59.99, 'Digitube', 'Hewe Pitcaithley', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('24/04/2025', 97, 'Children''s Musical Instrument Set', 84, 39.99, 'Yodo', 'Olva Doone', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('18/04/2025', 98, 'Solar Power Bank', 78, 39.99, 'Flashset', 'Kalle Feveryear', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('18/09/2025', 99, 'Oatmeal Raisin Cookies', 57, 3.49, 'Kwilith', 'Paule Fountain', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('17/08/2025', 100, 'Mint Chocolate Chip Ice Cream', 66, 4.99, 'Flashpoint', 'Lorilee Hull', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('01/12/2025', 101, 'Yoga Strap', 43, 12.99, 'Riffwire', 'Nikaniki Gowans', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('28/07/2025', 102, 'Snap-On Tupperware Set', 92, 34.99, 'Pixope', 'Camile Silman', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('11/03/2025', 103, 'Party Mini Dress', 62, 69.99, 'Shuffledrive', 'Mitchell Iacovazzi', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('16/08/2025', 104, 'Watercolor Paint Set', 65, 19.99, 'Zoomlounge', 'Sherye Hefferan', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('12/08/2025', 105, 'Apple Sauce', 50, 2.19, 'Ntag', 'Tyne Nowland', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('10/09/2025', 106, 'Non-Toxic Crayons for Kids', 38, 10.99, 'Yakidoo', 'Waverly McEwan', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('24/07/2025', 107, 'Chocolate Fudge Brownie Mix', 99, 2.99, 'Ozu', 'Shayna Ashburne', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('30/12/2025', 108, 'Pesto Genovese', 93, 6.49, 'Livetube', 'Roby Hovington', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('19/11/2025', 109, 'Salsa', 73, 3.49, 'Wikido', 'Lee Cartledge', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('31/10/2025', 110, 'Mango Chunks', 75, 4.89, 'Yoveo', 'Mitchael Foulcher', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('23/06/2025', 111, 'Leek and Potato Soup', 82, 3.29, 'Twitterwire', 'Gallard Corley', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('21/04/2025', 112, 'Summer Tank Dress', 56, 39.99, 'Teklist', 'Nettle Lochran', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('10/08/2025', 113, 'Organic Whole Grain Oats', 55, 2.49, 'Zooveo', 'Maurise Benoiton', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('21/02/2025', 114, 'Smart WiFi Plug', 53, 19.99, 'Avamm', 'Emmy Openshaw', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('07/06/2025', 115, 'Coconut Curry Lentil Soup', 66, 3.99, 'Mycat', 'Halimeda Hoys', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('05/07/2025', 116, 'Organic Coconut Flour', 27, 5.49, 'Skajo', 'Manfred Huxster', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('20/04/2025', 117, 'Classic Vanilla Fudge', 98, 4.49, 'Mycat', 'Jaimie Monsey', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('15/12/2025', 118, 'Jalapeño Cornbread', 17, 3.29, 'Photobean', 'Eustace Twelvetree', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('22/04/2025', 119, 'Ginger Snaps', 9, 2.79, 'Yambee', 'Stacee Chasmoor', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('11/12/2025', 120, 'Lemon Pepper Seasoning', 48, 3.29, 'Snaptags', 'Haroun Cuffin', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('30/03/2025', 121, 'Cucumber', 99, 0.99, 'Skajo', 'Carilyn Adderley', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('25/01/2025', 122, 'Balsamic Glazed Brussels Sprouts', 94, 4.99, 'Kwideo', 'Carlynne Pencott', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('08/03/2025', 123, 'Olive Oil', 63, 7.99, 'Vidoo', 'Rikki Prose', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('08/05/2025', 124, 'Foldable Yoga Mat Carry Bag', 24, 18.99, 'Wikizz', 'Rosalynd Woofinden', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('29/03/2025', 125, 'Plaid Flannel Shirt', 5, 29.99, 'Npath', 'Beverie Valasek', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('19/03/2025', 126, 'Balsamic Vinaigrette', 8, 2.69, 'Riffpedia', 'Artemas Dinzey', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('17/09/2025', 127, 'Vegan Protein Powder', 42, 34.99, 'Oyoba', 'Justine O''Hallagan', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('05/11/2025', 128, 'Beef Sirloin Steak', 62, 15.99, 'Topiczoom', 'Rudolfo Cadagan', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('25/08/2025', 129, 'Chia Seed Pudding', 25, 3.99, 'Gevee', 'Barnabe Warmisham', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('09/07/2025', 130, 'Smart Home Hub', 92, 99.99, 'Leexo', 'Mandel Bridger', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('06/08/2025', 131, 'Crew Neck Sweater', 92, 39.99, 'Nlounge', 'Jordon Gallelli', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('23/04/2025', 132, 'Portable Camping Stove', 40, 49.99, 'Linkbridge', 'Debora Springer', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('05/07/2025', 133, 'Basketball', 43, 29.99, 'Browseblab', 'Wat Pinckstone', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('24/02/2025', 134, 'Outdoor String Lights', 45, 24.99, 'Roodel', 'Cass Martell', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('22/03/2025', 135, 'Digital Voice Recorder', 16, 49.99, 'Twitterbeat', 'Evvy Shorto', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('19/04/2025', 136, 'Roasted Sweet Corn', 54, 1.99, 'Eazzy', 'Raviv McChesney', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('22/05/2025', 137, 'Luxury Bath Robe', 20, 49.99, 'Wikivu', 'Carola Ligertwood', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('13/02/2025', 138, 'Canned Black Beans', 64, 1.29, 'Skimia', 'Luther Rapelli', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('19/06/2025', 139, 'Peach Yogurt', 84, 1.29, 'Realcube', 'Elsa Stelfax', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('11/12/2025', 140, 'Electric Skillet', 89, 49.99, 'Chatterbridge', 'Jodee Troni', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('24/11/2025', 141, 'Garlic Parmesan Wings', 81, 8.99, 'Trudeo', 'Hadrian Pepi', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('22/11/2025', 142, 'Heavy Duty Gardening Tool Set', 74, 49.99, 'Skipfire', 'Celestina Feldbaum', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('22/08/2025', 143, 'Coconut Chips', 41, 3.59, 'Centizu', 'Rivy Loadwick', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('20/04/2025', 144, 'Wireless Gaming Headset', 80, 89.99, 'Twitterlist', 'Marjy Kirkpatrick', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('09/12/2025', 145, 'Folding Pocket Knife', 8, 24.99, 'Avavee', 'Derron Adamovitz', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('15/10/2025', 146, 'Oats', 15, 3.29, 'Flipstorm', 'Turner Tassell', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('13/08/2025', 147, 'Non-Stick Grill Mat', 12, 19.99, 'Trupe', 'Meredithe Delagnes', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('10/02/2025', 148, 'Vegetable Stir-Fry Sauce', 71, 3.49, 'Blogpad', 'Loria Pennycord', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('27/05/2025', 149, 'Lentils', 7, 2.99, 'Jayo', 'Dillon Whitnall', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('02/11/2025', 150, 'Lemon Zest Olive Oil', 37, 8.99, 'Jaxbean', 'Charlotte Cawson', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('10/05/2025', 151, 'Cranberry Almond Cookies', 9, 4.29, 'Geba', 'Linea Blacklidge', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('28/03/2025', 152, 'Free-Range Eggs', 73, 3.99, 'LiveZ', 'Mella Dulanty', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('10/11/2025', 153, 'Vegan Tacos', 57, 7.49, 'Realcube', 'Karita Godsell', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('21/11/2025', 154, 'Chia Seeds', 9, 6.99, 'Meevee', 'Carrie Berger', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('25/06/2025', 155, 'Artisan Flatbreads', 85, 2.99, 'Eazzy', 'Nerissa Caverhill', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('12/10/2025', 156, 'Car Escape Tool', 92, 12.99, 'Einti', 'Vladamir Writer', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('11/02/2025', 157, 'Collapsible Water Bottle', 70, 12.99, 'Linkbridge', 'Jeramie Sleightholme', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('11/02/2025', 158, 'Honey-Balsamic Vinaigrette', 19, 3.39, 'Kayveo', 'Gray Branscomb', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('15/06/2025', 159, 'Children''s Educational Puzzle', 61, 19.99, 'Quimm', 'Sammie Hawkswood', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('07/03/2025', 160, 'Lemon Pepper Seasoning', 36, 3.29, 'Nlounge', 'Lindsy Davinet', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('02/03/2025', 161, 'Maple Almond Butter', 53, 5.49, 'LiveZ', 'Sansone Kunes', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('05/08/2025', 162, 'Wireless Printer', 4, 99.99, 'Katz', 'Carlos Brennen', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('21/06/2025', 163, 'Pasta Maker Machine', 25, 59.99, 'Feedbug', 'Dierdre Shawcross', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('22/07/2025', 164, 'Fresh Strawberries', 22, 3.99, 'Buzzbean', 'Pearle Beidebeke', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('19/04/2025', 165, 'Electric Rice Cooker', 13, 39.99, 'Photobug', 'Darelle Jaime', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('05/05/2025', 166, 'Compact Hair Dryer', 55, 29.99, 'Kare', 'Linea Bairnsfather', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('10/05/2025', 167, 'Cushion Covers', 45, 35, 'Skyble', 'Breena Boast', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('15/06/2025', 168, 'Tomato Basil Pasta Sauce', 92, 3.99, 'Centimia', 'Mira Monk', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('02/06/2025', 169, 'Sweet Corn', 84, 1.5, 'Dynazzy', 'Joaquin Robard', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('27/12/2025', 170, 'Training Soccer Ball', 8, 19.99, 'Innojam', 'Darsey Djekic', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('04/10/2025', 171, 'Peach Slices in Syrup', 68, 2.59, 'Rhyzio', 'Agata Dehmel', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('11/05/2025', 172, 'Water Bottle', 50, 18.99, 'Fivechat', 'Kelbee Barthelemy', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('20/11/2025', 173, 'Blue Denim Jeans', 31, 49.99, 'Tagtune', 'Babbie Bottby', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('11/10/2025', 174, 'Garlic Butter Sauce', 34, 3.59, 'Demivee', 'Tierney Lytle', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('18/04/2025', 175, 'Men''s Waterproof Hiking Boots', 76, 89.99, 'Cogidoo', 'Stirling Sneath', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('25/07/2025', 176, 'Peas (frozen)', 30, 1.89, 'Rooxo', 'Gail Snawden', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('13/09/2025', 177, 'Kettle Corn Popcorn', 75, 2.99, 'Zoombeat', 'Nickolas Bewly', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('28/09/2025', 178, 'Ergonomic Gaming Chair', 11, 199.99, 'Dynava', 'Trev Ivakin', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('31/03/2025', 179, 'Puff Pastry', 39, 5.49, 'Kazu', 'Georgi Caldwall', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('07/08/2025', 180, 'Raspberry Limeade', 80, 1.99, 'Tagfeed', 'Davin Riggey', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('09/09/2025', 181, 'Oven-Baked Potato Chips', 2, 2.79, 'Yozio', 'Osbourne Fernihough', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('18/09/2025', 182, 'Vegetable Stir Fry Mix', 23, 3.29, 'Layo', 'Craggy Bardnam', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('13/06/2025', 183, 'Video Camera', 38, 199, 'Gabvine', 'Waylen Marling', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('03/08/2025', 184, 'Magnetic Puzzle Board', 23, 24.99, 'Bubblebox', 'Jakob Moxham', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('04/09/2025', 185, 'Printed Maxi Skirt', 70, 39.99, 'Skalith', 'Alikee Fanti', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('25/08/2025', 186, 'Traditional Hummus', 34, 3.29, 'Roodel', 'Kim Tegler', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('30/05/2025', 187, 'Pineapple Coconut Bars', 41, 3.79, 'Zoovu', 'Jessalin MacHostie', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('07/11/2025', 188, 'Basmati Rice', 37, 5.79, 'Jetwire', 'Ryan Hawkins', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('18/08/2025', 189, 'Lemon Dill Chicken Skewers', 44, 9.99, 'Tazzy', 'Pearle Kilbey', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('25/10/2025', 190, 'Fitness Foam Roller', 79, 29.99, 'Meejo', 'Carlye Vasilov', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('01/08/2025', 191, 'Ski Goggles', 99, 49.99, 'Vinte', 'Ricardo Moorhead', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('08/02/2025', 192, 'Laptop Stand', 81, 29.99, 'Shuffletag', 'Mace Mohring', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('20/01/2025', 193, 'Rice Pilaf Mix', 82, 2.59, 'Quamba', 'Martie Torvey', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('03/03/2025', 194, 'Memory Foam Mattress Topper', 79, 109.99, 'Thoughtstorm', 'Maureene Peers', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('08/10/2025', 195, 'Electric Rice Cooker with Steamer', 37, 49.99, 'Skipstorm', 'Danita Rangeley', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('13/09/2025', 196, 'Artisan Flatbreads', 85, 2.99, 'Thoughtstorm', 'Shaylynn Checchetelli', 'out');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('02/04/2025', 197, 'Electric Blanket', 98, 59.99, 'Brainlounge', 'Terencio Redwin', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('13/03/2025', 198, 'Savory Oatmeal', 26, 2.49, 'Jabberbean', 'Dagny Brownjohn', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('06/07/2025', 199, 'Multifunctional Baby Bottle Warmer', 96, 39.99, 'Yambee', 'Elsie Niave', 'in');
insert into MOCK_SHIPPING_DATA (date, id, item, quantity, value, source_customer, responsible, in_out) values ('08/01/2026', 200, 'Wireless Earbuds Case', 95, 12.99, 'Katz', 'Walther Gilbey', 'in');
